INSERT INTO article
(TITLE, AUTHOR, CATEGORY, STATUS, PUBLICATION_DATE)
VALUES
    ('Spring Basics', 'John', 'Backend', 'PUBLISHED', '2025-01-15');

INSERT INTO article
(TITLE, AUTHOR, CATEGORY, STATUS, PUBLICATION_DATE)
VALUES
    ('React Guide', 'Anna', 'Frontend', 'DRAFT', '2025-02-20');

INSERT INTO article
(TITLE, AUTHOR, CATEGORY, STATUS, PUBLICATION_DATE)
VALUES
    ('JPA Tips', 'John', 'Backend', 'PUBLISHED', '2025-03-10');

INSERT INTO article
(TITLE, AUTHOR, CATEGORY, STATUS, PUBLICATION_DATE)
VALUES
    ('Docker Intro', 'Mike', 'DevOps', 'PUBLISHED', '2025-04-05');

INSERT INTO article
(TITLE, AUTHOR, CATEGORY, STATUS, PUBLICATION_DATE)
VALUES
    ('Testing Spring', 'Anna', 'Backend', 'PUBLISHED', '2025-05-12');